CREATE TABLE person (id INT AUTO_INCREMENT NOT NULL, firstName VARCHAR(25) NOT NULL, secondName VARCHAR(25) NOT NULL, age NUMERIC(10, 0) NOT NULL, membershipDate DATE NOT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE friends_relations (person_id INT NOT NULL, friend_id INT NOT NULL, INDEX IDX_7B31F771217BBB47 (person_id), INDEX IDX_7B31F7716A5458E8 (friend_id), PRIMARY KEY(person_id, friend_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE friendOf_relations (person_id INT NOT NULL, friend_id INT NOT NULL, INDEX IDX_6247F595217BBB47 (person_id), INDEX IDX_6247F5956A5458E8 (friend_id), PRIMARY KEY(person_id, friend_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE post (id INT AUTO_INCREMENT NOT NULL, person_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, publicationDate DATE NOT NULL, INDEX IDX_5A8A6C8D217BBB47 (person_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE friends_relations ADD CONSTRAINT FK_7B31F771217BBB47 FOREIGN KEY (person_id) REFERENCES person (id);
ALTER TABLE friends_relations ADD CONSTRAINT FK_7B31F7716A5458E8 FOREIGN KEY (friend_id) REFERENCES person (id);
ALTER TABLE friendOf_relations ADD CONSTRAINT FK_6247F595217BBB47 FOREIGN KEY (person_id) REFERENCES person (id);
ALTER TABLE friendOf_relations ADD CONSTRAINT FK_6247F5956A5458E8 FOREIGN KEY (friend_id) REFERENCES person (id);
ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D217BBB47 FOREIGN KEY (person_id) REFERENCES person (id);
